import { DEFAULT_PACKAGES } from "@/lib/constants";
import type { MatchHighlight, Prediction, Purchase } from "@/lib/types";

export const seedPredictions: Prediction[] = [
  {
    id: "daily-free-1",
    category: "daily",
    packageTier: null,
    homeTeam: "Arsenal",
    awayTeam: "Brentford",
    competition: "Premier League",
    kickoff: "2026-05-10T18:00:00.000Z",
    market: "Match Winner",
    odds: 1.62,
    pick: "Arsenal to win",
    confidence: "High",
    status: "Pending",
    insight: "Arsenal have won six straight home league matches with a +11 goal difference.",
    isFree: true,
    isPremium: false,
  },
  {
    id: "daily-free-2",
    category: "daily",
    packageTier: null,
    homeTeam: "Fiorentina",
    awayTeam: "Torino",
    competition: "Serie A",
    kickoff: "2026-05-10T19:45:00.000Z",
    market: "Both Teams To Score",
    odds: 1.74,
    pick: "BTTS - Yes",
    confidence: "Medium",
    status: "Pending",
    insight: "Both sides have scored in eight of the last ten combined league fixtures.",
    isFree: true,
    isPremium: false,
  },
  {
    id: "weekend-free-1",
    category: "weekend",
    packageTier: null,
    homeTeam: "PSG",
    awayTeam: "Lyon",
    competition: "Ligue 1",
    kickoff: "2026-05-11T20:00:00.000Z",
    market: "Over/Under",
    odds: 1.68,
    pick: "Over 2.5 Goals",
    confidence: "High",
    status: "Pending",
    insight: "PSG home fixtures are averaging 3.4 goals per game this season.",
    isFree: true,
    isPremium: false,
  },
  {
    id: "weekend-free-2",
    category: "weekend",
    packageTier: null,
    homeTeam: "Leverkusen",
    awayTeam: "Freiburg",
    competition: "Bundesliga",
    kickoff: "2026-05-11T16:30:00.000Z",
    market: "Double Chance",
    odds: 1.41,
    pick: "Leverkusen or Draw",
    confidence: "Medium",
    status: "Pending",
    insight: "Leverkusen remain unbeaten in their last nine matches across all competitions.",
    isFree: true,
    isPremium: false,
  },
  {
    id: "monthly-free-1",
    category: "monthly",
    packageTier: null,
    homeTeam: "Real Madrid",
    awayTeam: "Sevilla",
    competition: "La Liga",
    kickoff: "2026-05-17T19:00:00.000Z",
    market: "Asian Handicap",
    odds: 1.77,
    pick: "Real Madrid -1",
    confidence: "High",
    status: "Pending",
    insight: "Madrid have covered this line in four of their last five home league wins.",
    isFree: true,
    isPremium: false,
  },
  {
    id: "monthly-free-2",
    category: "monthly",
    packageTier: null,
    homeTeam: "Sporting CP",
    awayTeam: "Braga",
    competition: "Primeira Liga",
    kickoff: "2026-05-18T18:30:00.000Z",
    market: "Goals",
    odds: 1.73,
    pick: "Over 1.5 Goals",
    confidence: "Medium",
    status: "Pending",
    insight: "Both clubs rank top four in the league for big chances created.",
    isFree: true,
    isPremium: false,
  },
  ...Array.from({ length: 10 }, (_, index) => ({
    id: `daily-premium-${index + 1}`,
    category: "daily" as const,
    packageTier: (index < 4 ? 4 : index < 8 ? 8 : 10) as 4 | 8 | 10,
    homeTeam: ["Atletico Madrid", "Napoli", "Benfica", "Celtic", "Marseille", "Ajax", "Monaco", "Roma", "Porto", "Galatasaray"][index],
    awayTeam: ["Getafe", "Bologna", "Rio Ave", "Hearts", "Nantes", "AZ Alkmaar", "Nice", "Udinese", "Boavista", "Kasimpasa"][index],
    competition: ["La Liga", "Serie A", "Liga Portugal", "Scottish Premiership", "Ligue 1", "Eredivisie", "Ligue 1", "Serie A", "Liga Portugal", "Super Lig"][index],
    kickoff: new Date(Date.UTC(2026, 4, 10 + Math.floor(index / 2), 17 + (index % 3), 0, 0)).toISOString(),
    market: ["Match Winner", "Draw No Bet", "BTTS", "Over/Under", "Match Winner", "BTTS", "Asian Handicap", "Double Chance", "Match Winner", "Goals"][index],
    odds: Number((1.58 + index * 0.09).toFixed(2)),
    pick: ["Atletico to win", "Napoli DNB", "BTTS - Yes", "Over 2.5 Goals", "Marseille to win", "BTTS - Yes", "Monaco -0.5", "Roma or Draw", "Porto to win", "Over 2.5 Goals"][index],
    confidence: index < 4 ? "High" : index < 8 ? "Medium" : "Speculative",
    status: "Pending" as const,
    insight: "Model edge driven by form, xG trend, and market resistance against late price drift.",
    isFree: false,
    isPremium: true,
  })),
  ...Array.from({ length: 10 }, (_, index) => ({
    id: `weekend-premium-${index + 1}`,
    category: "weekend" as const,
    packageTier: (index < 4 ? 4 : index < 8 ? 8 : 10) as 4 | 8 | 10,
    homeTeam: ["Inter", "Chelsea", "Bayern", "Juventus", "Dortmund", "Lille", "Athletic Club", "Fenerbahce", "PSV", "Lazio"][index],
    awayTeam: ["Sassuolo", "Brighton", "Augsburg", "Verona", "Mainz", "Reims", "Osasuna", "Rizespor", "Twente", "Genoa"][index],
    competition: ["Serie A", "Premier League", "Bundesliga", "Serie A", "Bundesliga", "Ligue 1", "La Liga", "Super Lig", "Eredivisie", "Serie A"][index],
    kickoff: new Date(Date.UTC(2026, 4, 12 + Math.floor(index / 2), 14 + (index % 4), 30, 0)).toISOString(),
    market: ["Match Winner", "Goals", "Asian Handicap", "Double Chance", "BTTS", "Match Winner", "Under 3.5", "Match Winner", "Goals", "BTTS"][index],
    odds: Number((1.61 + index * 0.1).toFixed(2)),
    pick: ["Inter to win", "Over 2.5 Goals", "Bayern -1", "Juventus or Draw", "BTTS - Yes", "Lille to win", "Under 3.5 Goals", "Fenerbahce to win", "Over 1.5 Goals", "BTTS - Yes"][index],
    confidence: index < 4 ? "High" : index < 8 ? "Medium" : "Speculative",
    status: "Pending" as const,
    insight: "Premium weekend card stacks price inefficiencies from major European league fixtures.",
    isFree: false,
    isPremium: true,
  })),
  ...Array.from({ length: 10 }, (_, index) => ({
    id: `monthly-premium-${index + 1}`,
    category: "monthly" as const,
    packageTier: (index < 4 ? 4 : index < 8 ? 8 : 10) as 4 | 8 | 10,
    homeTeam: ["Barcelona", "AC Milan", "Leeds", "Trabzonspor", "Flamengo", "Palmeiras", "Club Brugge", "Al Ahly", "River Plate", "Boca Juniors"][index],
    awayTeam: ["Valencia", "Atalanta", "Hull City", "Sivasspor", "Gremio", "Santos", "Gent", "Pyramids", "Racing Club", "San Lorenzo"][index],
    competition: ["La Liga", "Serie A", "Championship", "Super Lig", "Brazil Serie A", "Brazil Serie A", "Belgian Pro League", "Egyptian Premier League", "Liga Profesional", "Liga Profesional"][index],
    kickoff: new Date(Date.UTC(2026, 4, 15 + Math.floor(index / 2), 15 + (index % 5), 15, 0)).toISOString(),
    market: ["Match Winner", "BTTS", "Double Chance", "Goals", "Asian Handicap", "Match Winner", "BTTS", "Under 3.5", "Match Winner", "Goals"][index],
    odds: Number((1.66 + index * 0.11).toFixed(2)),
    pick: ["Barcelona to win", "BTTS - Yes", "Leeds or Draw", "Over 2.5 Goals", "Flamengo -0.5", "Palmeiras to win", "BTTS - Yes", "Under 3.5 Goals", "River Plate to win", "Over 1.5 Goals"][index],
    confidence: index < 4 ? "High" : index < 8 ? "Medium" : "Speculative",
    status: "Pending" as const,
    insight: "Longer-range card blends top-flight and elite regional spots with stable liquidity.",
    isFree: false,
    isPremium: true,
  })),
];

export const seedMatchHighlights: MatchHighlight[] = [
  {
    id: "highlight-1",
    title: "Arsenal press advantage vs Brentford's low block",
    fixture: "Arsenal vs Brentford",
    competition: "Premier League",
    kickoff: "2026-05-10T18:00:00.000Z",
    angle: "Expect sustained territory and set-piece volume from Arsenal.",
    summary: "Brentford concede repeat second-ball opportunities away from home. Arsenal's left-side overload remains their cleanest route to early control.",
    status: "Pending",
  },
  {
    id: "highlight-2",
    title: "PSG home tempo points to overs",
    fixture: "PSG vs Lyon",
    competition: "Ligue 1",
    kickoff: "2026-05-11T20:00:00.000Z",
    angle: "High press, transition speed, and weak defensive spacing support a goals angle.",
    summary: "PSG's chance creation against top-half visitors remains the strongest in France, while Lyon's away xGA trend stays elevated.",
    status: "Pending",
  },
  {
    id: "highlight-3",
    title: "Madrid handicap value still holding",
    fixture: "Real Madrid vs Sevilla",
    competition: "La Liga",
    kickoff: "2026-05-17T19:00:00.000Z",
    angle: "Look for control through midfield progression and repeat cutback chances.",
    summary: "Sevilla have struggled against elite press resistance, while Madrid continue to generate the most box entries in the league.",
    status: "Pending",
  },
];

export const seedPackages = DEFAULT_PACKAGES;
export const seedPurchases: Purchase[] = [];
